# Dictionary mapping shortened team names to their full names
TEAM_MAP = {
    # Champions League Teams
    'BVB': 'Borussia Dortmund',
    'SCP': 'Sporting Lisbon',
    'RMA': 'Real Madrid',
    'MCI': 'Manchester City',
    'PSG': 'Paris Saint-Germain',
    'BRE': 'Brentford',
    'PSV': 'PSV',
    'JUV': 'Juventus',
    'BAR': 'Barcelona',
    'INT': 'Inter',
    'NAP': 'Napoli',
    'BAY': 'Bayern Munich',
    'ATM': 'Atlético Madrid',
    'BEN': 'Benfica',
    'POR': 'Porto',
    'LAZ': 'Lazio',
    
    # Premier League Teams
    'AVL': 'Aston Villa',
    'LIV': 'Liverpool',
    'LEI': 'Leicester',
    'WHU': 'West Ham',
    'ARS': 'Arsenal',
    'BOU': 'Bournemouth',
    'CRY': 'Crystal Palace',
    'EVE': 'Everton',
    'MUN': 'Manchester United',
    'TOT': 'Tottenham',
    'WOL': 'Wolves',
    'BHA': 'Brighton',
    'NEW': 'Newcastle',
    'NFO': 'Nottingham Forest',
    'FUL': 'Fulham',
    'SOU': 'Southampton',
    'CHE': 'Chelsea',
    'BUR': 'Burnley',
    'SHU': 'Sheffield United',
    'LUT': 'Luton',
    
    # Bundesliga Teams
    'SCF': 'SC Freiburg',
    'WER': 'Werder Bremen',
    'LEV': 'Bayer Leverkusen',
    'BMG': 'Borussia Mönchengladbach',
    'SGE': 'Eintracht Frankfurt',
    'VFB': 'VfB Stuttgart',
    'WOB': 'VfL Wolfsburg',
    'BSC': 'Hertha BSC',
    'FCN': '1. FC Nürnberg',
    'HSV': 'Hamburger SV',
    'FCK': '1. FC Kaiserslautern',
    'KIE': 'Holstein Kiel',
    
    # La Liga Teams
    'CEL': 'Celta Vigo',
    'OSA': 'Osasuna',
    'VAL': 'Valencia',
    'SEV': 'Sevilla',
    'VIL': 'Villarreal',
    'GET': 'Getafe',
    'RSO': 'Real Sociedad',
    'BET': 'Real Betis',
    'LPA': 'UD Las Palmas',
    'GIR': 'Girona',
    'ALM': 'Almería',
    'CAD': 'Cádiz',
    'GRN': 'Granada',
    'MAL': 'RCD Mallorca',
    
    # Serie A Teams
    'MIL': 'AC Milan',
    'ROM': 'AS Roma',
    'UDI': 'Udinese',
    'FIO': 'Fiorentina',
    'GEN': 'Genoa',
    'TOR': 'Torino',
    'BOL': 'Bologna',
    'LEC': 'Lecce',
    'VEN': 'Venezia',
    'SAL': 'Salernitana',
    'CAG': 'Cagliari',
    'EMP': 'Empoli',
    'SAS': 'Sassuolo',
    'FRO': 'Frosinone',
    
    # Eredivisie Teams
    'AJX': 'Ajax',
    'FEY': 'Feyenoord',
    'PSV': 'PSV',
    'AZA': 'AZ Alkmaar',
    'TWE': 'FC Twente',
    'UTR': 'FC Utrecht',
    'VIT': 'Vitesse',
    'HEE': 'SC Heerenveen',
    'GRO': 'FC Groningen',
    'GAE': 'Go Ahead Eagles',
    'SPA': 'Sparta Rotterdam',
    'NEC': 'NEC Nijmegen',
    'FOR': 'Fortuna Sittard',
    'PEC': 'PEC Zwolle',
    'EXC': 'Excelsior Rotterdam',
    'HEL': 'Helmond Sport',
    'TEL': 'SC Telstar',
    'GRA': 'De Graafschap',
    'JAZ': 'Jong AZ Alkmaar',
    'ROD': 'Roda JC Kerkrade',
    'DBO': 'FC Den Bosch',
    'TOP': 'TOP Oss',
    'EMM': 'FC Emmen',
    'ALM': 'Almere City',
    
    # French Ligue 1 Teams
    'PSG': 'Paris Saint-Germain',
    'OL': 'Olympique Lyon',
    'OM': 'Olympique Marseille',
    'REN': 'Rennes',
    'LIL': 'LOSC Lille',
    'MON': 'AS Monaco',
    'LEN': 'RC Lens',
    'REI': 'Reims',
    'NIC': 'OGC Nice',
    'STR': 'Strasbourg',
    'NAN': 'FC Nantes',
    'BRE': 'Stade Brest',
    
    # Belgian Pro League Teams
    'AND': 'Anderlecht',
    'CLU': 'Club Brugge',
    'GNK': 'KRC Genk',
    'GEN': 'KAA Gent',
    'STD': 'Standard Liège',
    'MEC': 'KV Mechelen',
    'STR': 'Sint-Truiden',
    'CHA': 'Charleroi',
    'KVO': 'KV Oostende',
    'KVK': 'KV Kortrijk',
    
    # Portuguese Primeira Liga Teams
    'SLB': 'Benfica',
    'FCP': 'FC Porto',
    'SCP': 'Sporting CP',
    'SCB': 'S.C. Braga',
    'VTG': 'Vitória Guimarães',
    'MAR': 'Marítimo',
    'NAC': 'Nacional Madeira',
    'BOA': 'Boavista',
    
    # Turkish Süper Lig Teams
    'GS': 'Galatasaray',
    'FB': 'Fenerbahçe',
    'BJK': 'Beşiktaş',
    'TS': 'Trabzonspor',
    'BSK': 'Başakşehir',
    'ADA': 'Adana Demirspor',
    'EYU': 'Eyüpspor',
    
    # Europa League Teams
    'ROM': 'Roma',
    'AZ': 'AZ Alkmaar',
    'AND': 'Anderlecht',
    'FCM': 'Midtjylland',
    
    # Additional Teams
    'PLZ': 'Viktoria Plzen',
    'FTC': 'Ferencvaros',
    'FCS': 'Sparta Prague',

    # Additional English Teams
    'HUD': 'Huddersfield Town',
    'IPS': 'Ipswich Town',
    'BRO': 'Bristol Rovers',
    'TRN': 'Tranmere Rovers',
    'ACC': 'Accrington Stanley',
    'CHA': 'Charlton Athletic',
    'WAL': 'Walsall',
    'GIL': 'Gillingham',
    'FLE': 'Fleetwood Town',
    'WIG': 'Wigan Athletic',
    'BIR': 'Birmingham City',
    'LEY': 'Leyton Orient',
    'NOR': 'Northampton Town',
    'CAR': 'Cardiff City',
    'HUL': 'Hull City',
    'STK': 'Stoke City',
    'MID': 'Middlesbrough',
    'CRE': 'Crewe Alexandra',
    'MAL': 'RCD Mallorca',
    
    # Additional Italian Teams
    'ASM': 'AS Monaco',  # Changed from MON to ASM for Monaco

    # Additional Serie A Teams
    'ACM': 'AC Milan',  # Alternative code for Milan
    'ASR': 'AS Roma',   # Alternative code for Roma
    'INT': 'Inter Milan',  # Alternative name
    'PAR': 'Parma',
    'SPE': 'Spezia',
    'VER': 'Hellas Verona',
    'MNZ': 'Monza',     # Changed from MON to MNZ
    'SAM': 'Sampdoria',
    
    # Additional English Lower Division Teams    
    'BLA': 'Blackburn Rovers',
    'MIL': 'Millwall',
    'ROT': 'Rotherham United',
    'SWA': 'Swansea City',
    'QPR': 'Queens Park Rangers',
    'PNE': 'Preston North End',
    'COV': 'Coventry City',
    'WAT': 'Watford',
    'BRI': 'Bristol City',
    'PET': 'Peterborough United',
    'PLY': 'Plymouth Argyle',
    'OXF': 'Oxford United',
    'POR': 'Portsmouth',
    'SHW': 'Shrewsbury Town',
    'WYC': 'Wycombe Wanderers',
    'MKD': 'MK Dons',
    'AFC': 'AFC Wimbledon',
    'DON': 'Doncaster Rovers',
    'BFC': 'Bradford City',  # Changed from BRA to BFC
    'MAF': 'Mansfield Town',
    'NPC': 'Newport County', # Changed from NEW to NPC
    'COL': 'Colchester United',
    'CRA': 'Crawley Town',
    'SUT': 'Sutton United',
    'ROC': 'Rochdale',
    'HAR': 'Hartlepool United',
    'STF': 'Stevenage',
    'SAL': 'Salford City',
    'BRW': 'Barrow',

    # Additional Alternative Names and Missing Teams
    'FCB': 'Bayern München',  # Alternative for Bayern Munich
    'SR': 'Stade Reims',     # Alternative for Reims
    'VLD': 'Valladolid',
    'LPM': 'UD Las Palmas',  # Alternative for Las Palmas
    'SUN': 'Sunderland',
    'WBA': 'West Bromwich Albion',
    'DER': 'Derby County',
    'COM': 'Como',
    'ESP': 'Espanyol',
    'HAC': 'Le Havre',
    'ATH': 'Athletic Bilbao',
    'TFC': 'Toulouse',
    'BPL': 'Blackpool',
    'RCL': 'RC Lens',        # Alternative for Lens
    'ASS': 'AS Saint-Étienne',
    'LEG': 'Leganés',
    'MLL': 'Mallorca',       # Alternative for RCD Mallorca
    'ALA': 'Alavés',
    'RAY': 'Rayo Vallecano',
    'HDH': 'Heidenheim',
    'TSG': 'Hoffenheim',
    'M05': 'Mainz 05',       # Alternative for Mainz
    'SVW': 'Werder Bremen',  # Alternative for Bremen
    'BOC': 'Bochum',
    'FCU': 'Union Berlin',
    'KSV': 'Holstein Kiel',  # Alternative for Kiel
    'STP': 'St. Pauli',
    'CLT': 'Cheltenham Town',
    'GRI': 'Grimsby Town',
    'NOT': 'Notts County',
    'MOR': 'Morecambe',
    'NTH': 'Northampton',    # Alternative for Northampton Town
    'SHR': 'Shrewsbury',     # Alternative for Shrewsbury Town
    'REA': 'Reading',
    'CAM': 'Cambridge United',
    'EXE': 'Exeter City',
    'BTN': 'Burton Albion',
    'MAN': 'Mansfield',      # Alternative for Mansfield Town
    'LIN': 'Lincoln City',
    'CHF': 'Chesterfield',
    
    # Lower division competition codes
    'LET': 'League Two',
    'LEO': 'League One',
    'CHA': 'Championship',

    # Additional Abbreviations Found
    'LEE': 'Leeds United',
    'WRE': 'Wrexham',
    'NPT': 'Newport County',
    'SWI': 'Swindon Town',
    'BRR': 'Bristol Rovers',
    'WIM': 'AFC Wimbledon',
    'TRA': 'Tranmere Rovers',
    'PVL': 'Port Vale',
    'STE': 'Stevenage',
    'STO': 'Stoke City',
    'AJA': 'Ajax',
    'SCO': 'SCO Angers',
    'FCA': 'FC Augsburg',
    
    # Additional Alternative Names
    'Bayern': 'Bayern München',
    'Inter': 'Inter Milan',
    'Bremen': 'Werder Bremen',
    'Monaco': 'AS Monaco',
    'Nice': 'OGC Nice',
    'Lyon': 'Olympique Lyon',
    'Marseille': 'Olympique Marseille',
    'PSV Eindhoven': 'PSV',

    # Additional German Teams
    'RBL': 'RB Leipzig',
    'FCK': 'FC Köln',
    'BSC': 'Hertha Berlin',
    'WOB': 'Wolfsburg',
    'SGE': 'Frankfurt',
    'B04': 'Bayer Leverkusen',
    'BMG': 'Mönchengladbach',
    'FCA': 'Augsburg',
    'SCF': 'Freiburg',
    'TSG': 'Hoffenheim',
    'FCU': 'Union Berlin',
    'M05': 'Mainz',
    'VFB': 'Stuttgart',
    'BOC': 'Bochum',
    'KOE': 'FC Köln',
    
    # Additional French Teams
    'PSG': 'Paris Saint Germain',
    'ASM': 'Monaco',
    'OGC': 'Nice',
    'LOSC': 'Lille',
    'SCO': 'Angers',
    'FCL': 'Lorient',
    'FCN': 'Nantes',
    'SB29': 'Brest',
    'MHSC': 'Montpellier',
    'RCL': 'Lens',
    'SRFC': 'Rennes',
    'FCM': 'Metz',
    'HAC': 'Le Havre',
    
    # Alternative Names
    'Leipzig': 'RB Leipzig',
    'Mönchengladbach': 'Borussia Mönchengladbach',
    'Gladbach': 'Borussia Mönchengladbach',
    'Frankfurt': 'Eintracht Frankfurt',
    'Wolfsburg': 'VfL Wolfsburg',
    'Lille': 'LOSC Lille',
    'PSG': 'Paris Saint-Germain',
    'Monaco': 'AS Monaco',
    'Nice': 'OGC Nice',
    'Lens': 'RC Lens',
    'Rennes': 'Stade Rennes',
    'Nantes': 'FC Nantes',
    'Brest': 'Stade Brest',
    'Leipzig': 'RB Leipzig',
    'Mainz': 'Mainz 05',

    # Alternative Variations
    'Eintracht': 'Eintracht Frankfurt',
    'Leverkusen': 'Bayer Leverkusen',
    'Hertha': 'Hertha Berlin',
    'Union': 'Union Berlin',
    'Augsburg': 'FC Augsburg',
    'Freiburg': 'SC Freiburg',
    'Stuttgart': 'VfB Stuttgart',
    'Holstein': 'Holstein Kiel',
}